### ISSUE TITLE
Lỗi lấy api 504

### ISSUE THREAD

**Issue by DatHip** [phamhiep2506/music-player#4]
bác ơi . bác check api hộ em xem em get toàn ăn lỗi 504. em lấy api từ nguồn bác mà giờ cbi cho buổi bảo vệ huhu

**Comment by phamhiep2506** [comment]
> bác ơi . bác check api hộ em xem em get toàn ăn lỗi 504. em lấy api từ nguồn bác mà giờ cbi cho buổi bảo vệ huhu

Bạn check lại nhé. Tại server free lên hơi chậm 😘. Chúc bạn bải vệ đồ án tốt nhé 🥰
